import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="flex justify-center text-5xl">swfz tools</h1>
        <div>
          主に自分用の便利ツール集
        </div>
      </main>

      <footer className="absolute bottom-0">
        <a
          href="https://github.com/swfz"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            swfz
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
