name: lint

on:
  push

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: run eslint
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: eslint check
        run: |
          pnpm lint

  prettier:
    runs-on: ubuntu-latest
    name: run prettier check
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: prettier check
        run: |
          pnpm lint:format

  slack-notify:
    if: always()
    needs: [eslint, prettier]
    name: post slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@2e709ce51fd47f02b7221db8547e6e6f49f81f1d # v2.0.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: swfz/failed-log-to-slack-action@06a3e089a86ca7114c7f8dba450dded18bb1936a # v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}


